# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projectTarget: 'Source/Dws.Template.Domain.Common/Dws.Template.Domain.Common.csproj'
  buildConfiguration: 'Release'
  coreCliVersion: 3.1.300
  runTime: 'win10-x64'

steps:

##### INSTALL DOTNET #######

- task: DotNetCoreInstaller@1
  displayName: 'Installing NetCore version $(coreCliVersion)...'
  inputs:
    version: $(coreCliVersion)


##### BUILD NET CORE #######

- task: DotNetCoreCLI@2
  displayName: 'Building Core CLI...'
  inputs:
    command: build
    projects: $(projectTarget)
    configuration: $(buildConfiguration)


##### NUGET #######


##- task: DotNetCoreCLI@2
##  inputs:
##    command: 'pack'
##    packagesToPack: '$(projectTarget)'
##    packDirectory: '$(Build.ArtifactStagingDirectory)'
##    includesymbols: true
##    majorVersion: '@Version.Major'
##    minorVersion: '@Version.Minor'
##    buildVersion: '$(Build.BuildNumber)'


- script: dotnet pack $(projectTarget) -p:PackageVersion=@Version.Major.@Version.Minor.@Version.Build.$(Build.BuildId) --output $(Build.ArtifactStagingDirectory) --include-symbols
  displayName: 'DotNet Pack'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '@Devops.FeedId'
    publishPackageMetadata: false
    allowPackageConflicts: true